name: 'Gitar Duet Action'
description: 'Automates the Gitar Duet process for pull requests'
inputs:
  github-token:
    description: 'GitHub token for authentication. Make sure it has `content:write` scope.'
    default: ${{ github.token }}
  verbose:
    description: 'Verbose output'
    default: false
runs:
  using: "composite"
  steps:
    - name: Get Pull Request Number
      id: duet
      run: |
        if [[ ${{ inputs.verbose }} == true ]]; then
          git --no-pager log -1 HEAD
        fi
        echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - run: |
        if [[ ${{ inputs.verbose }} == true ]]; then
          set -x
        fi

        if [[ -n $(git status --porcelain) ]]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Gitar Duet for #${{ steps.duet.outputs.pull_request_number }}"
          git checkout -b "gitar_duet_${{ steps.duet.outputs.pull_request_number }}"
          git push origin "gitar_duet_${{ steps.duet.outputs.pull_request_number }}"
        else
          echo "No changes to commit"
        fi
      shell: bash
      if: github.event.head_commit.author.name == 'Gitar' && steps.duet.outputs.pull_request_number != ''
    - run: |
        echo "Skipping Gitar Duet Action"
        if [[ ${{ inputs.verbose }} == true ]]; then
          echo "👼 Author: ${{ github.event.head_commit.author.name }}"
          echo "☝️ Pull Request: ${{ steps.duet.outputs.pull_request_number }}"
        fi
      shell: bash
      if: github.event.head_commit.author.name != 'Gitar' || steps.duet.outputs.pull_request_number == ''
