name: 'Gitar Duet Action'
description: 'Automates the Gitar Duet process for pull requests'
inputs:
  token:
    description: 'GitHub token for authentication. Make sure it has `content:write` scope.'
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Get Pull Request Number
      id: duet
      run: |
        echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - run: |
        if [[ -n $(git status --porcelain) ]]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Gitar Duet for #${{ steps.duet.outputs.pull_request_number }}"
          git checkout -b gitar_duet_${{ steps.duet.outputs.pull_request_number }}"
          git push origin gitar_duet_${{ steps.duet.outputs.pull_request_number }}"
        else
          echo "No changes to commit"
        fi
      shell: bash
      if: github.event.head_commit.author.name == 'Gitar' && steps.duet.outputs.pull_request_number != ''
